/** Enum containing special characters */
export enum SpecialCharacters {
  APOSTROPHE = "'",
  EN_DASH = "\u2013",
  EM_DASH = "\u2014",
  EMPTY_STRING = "",
  HYPHEN = "-",
  LEFT_DOUBLE_QUOTE = "\u201C",
  LEFT_SINGLE_QUOTE = "\u2018",
  LINE_BREAK = "<br>",
  MARKER = "\u001F",
  NEWLINE = "\n",
  NON_BREAKING_SPACE = "\u00A0",
  PARAGRAPH_TAG = "p",
  QUOTATION_MARK = '"',
  RIGHT_DOUBLE_QUOTE = "\u201D",
  RIGHT_SINGLE_QUOTE = "\u2019",
  SOFT_HYPHEN = "\u00AD",
  SPACE = "\u0020",
  SPAN_TAG = "span",
  STYLE_TAG = "style",
  TAB = "\t",
  VERTICAL_TAB = "\u000b",
  ZERO_WIDTH_SPACE = "\u200B",
}
