name: 'Test Report'
on:
  workflow_run:
    workflows: ['Test and Build'] # runs after CI workflow
    branches:
      - dev
      - main
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    # Only run if the workflow_run succeeded AND it was triggered by a PR
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'

    name: Generate Test Reports
    runs-on: ubuntu-latest

    steps:
    - name: Generate JEST test report
      uses: dorny/test-reporter@v2
      with:
        artifact: test-reports
        name: JEST Tests
        path: 'reports/jest/report.xml'
        reporter: jest-junit
    - name: Generate E2E test report
      uses: dorny/test-reporter@v2
      with:
        artifact: test-reports
        name: E2E Tests
        path: 'reports/playwright/report.xml'
        reporter: jest-junit
