name: 'Test Report'
on:
  workflow_run:
    workflows: ['Build App']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@6e6a65b7a0bd2c9197df7d0ae36ac5cee784230c # v2
      with:
        artifact: test-results            # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results
    - uses: dorny/test-reporter@6e6a65b7a0bd2c9197df7d0ae36ac5cee784230c # v2
      with:
        artifact: playwright-report            # artifact name
        name: E2E Tests                  # Name of the check run which will be created
        path: 'playwright-report.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results
