name: Run Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    name: Run Jest Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 'lts/*'  # Use latest LTS version

      - run: npm ci  # Uses package-lock.json for reproducible installs
      - run: npm run test:unit:ci

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: "reports/report.xml"
          reporter: jest-junit        # Format of test results
